### ISSUE TITLE
401 Client Error: UNAUTHORIZED for url: https://www.zopim.com/api/v2/departments

### ISSUE THREAD

**Issue by TomaszE** [singer-io/tap-zendesk-chat#17]
Hi guys - i got another issue with integration:

2019-02-11 09:59:26,816Z   main - INFO Running tap-zendesk-chat version 0.1.16 and target-stitch version 1.8.1
2019-02-11 09:59:26,882Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-zendesk-chat --config /tmp/tap_discover_config.json --discover
2019-02-11 09:59:27,202Z    tap - INFO HTTP request to "departments" endpoint took 0.133s, returned status code 401
2019-02-11 09:59:27,202Z    tap - CRITICAL 401 Client Error: UNAUTHORIZED for url: https://www.zopim.com/api/v2/departments
2019-02-11 09:59:27,202Z    tap - Traceback (most recent call last):
2019-02-11 09:59:27,203Z    tap -   File "tap-env/bin/tap-zendesk-chat", line 10, in <module>
2019-02-11 09:59:27,203Z    tap -     sys.exit(main())
2019-02-11 09:59:27,203Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 112, in main
2019-02-11 09:59:27,203Z    tap -     raise exc
2019-02-11 09:59:27,203Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 109, in main
2019-02-11 09:59:27,203Z    tap -     main_impl()
2019-02-11 09:59:27,203Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 99, in main_impl
2019-02-11 09:59:27,203Z    tap -     discover(args.config).dump()
2019-02-11 09:59:27,203Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 56, in discover
2019-02-11 09:59:27,203Z    tap -     ensure_credentials_are_authorized(client)
2019-02-11 09:59:27,204Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 33, in ensure_credentials_are_authorized
2019-02-11 09:59:27,204Z    tap -     client.request(streams_.DEPARTMENTS.tap_stream_id)
2019-02-11 09:59:27,204Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2019-02-11 09:59:27,204Z    tap -     ret = target(*args, **kwargs)
2019-02-11 09:59:27,204Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/http.py", line 34, in request
2019-02-11 09:59:27,204Z    tap -     response.raise_for_status()
2019-02-11 09:59:27,204Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 940, in raise_for_status
2019-02-11 09:59:27,204Z    tap -     raise HTTPError(http_error_msg, response=self)
2019-02-11 09:59:27,204Z    tap - requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://www.zopim.com/api/v2/departments
2019-02-11 09:59:27,222Z   main - INFO Tap exited abnormally with status 1
2019-02-11 09:59:27,223Z   main - INFO Exit status is: Discovery failed with code 1 and error message: "401 Client Error: UNAUTHORIZED for url: https://www.zopim.com/api/v2/departments".

**Comment by sarandeeps** [comment]
Hi, I am currently facing the same issue "401 Client Error: UNAUTHORIZED for url: https://www.zopim.com/api/v2/departments"
Can someone guide me to resolve the same.

**Comment by TomaszE** [comment]
I am getting the same issue - I will be grateful for help here.

**Comment by Fullmight** [comment]
Same issue here, doesn't work on any accounts with token or password access. Absolutely maddening for something that should be easy to access using the official documentation for the curl request, but that does not work and neither does doing this through postman.
