### ISSUE TITLE
Integration error

### ISSUE THREAD

**Issue by TomaszE** [singer-io/tap-zendesk-chat#6]
Hi , we have set up the integration yesterday, on the first run and every run after we are getting below error 
`400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251`

We have set up the integration to get data since 01/01/2016 but in table chats I have exactly 10k rows going back to 25th Nov 2017, and no new data are being replicated ( for example for yesterday I have only 10% data up to 9AM GMT - where we started the sync.)

**Comment by TomaszE** [comment]
Full log:


2018-02-08 21:45:18,422Z   main - INFO Running tap-zendesk-chat version 0.1.9 and target-stitch version 1.7.0
2018-02-08 21:45:18,539Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-zendesk-chat --config /tmp/tap_discover_config.json --discover
2018-02-08 21:45:19,378Z    tap - INFO HTTP request to "departments" endpoint took 0.573s, returned status code 200
2018-02-08 21:45:19,802Z    tap - INFO HTTP request to "account" endpoint took 0.423s, returned status code 403
2018-02-08 21:45:19,802Z    tap - INFO Ignoring 403 from account endpoint - this must be an integrated Zendesk account. This endpoint will be excluded from discovery.
2018-02-08 21:45:19,848Z   main - INFO Tap exited normally.
2018-02-08 21:45:19,849Z   main - INFO Saving list of discovered streams
2018-02-08 21:45:19,892Z   main - INFO Saving structure of stream agents
2018-02-08 21:45:19,972Z   main - INFO Saving structure of stream chats
2018-02-08 21:45:19,987Z   main - INFO Saving structure of stream shortcuts
2018-02-08 21:45:19,997Z   main - INFO Saving structure of stream triggers
2018-02-08 21:45:20,011Z   main - INFO Saving structure of stream bans
2018-02-08 21:45:20,024Z   main - INFO Saving structure of stream departments
2018-02-08 21:45:20,041Z   main - INFO Saving structure of stream goals
2018-02-08 21:45:20,053Z   main - INFO Getting list of selected properties
2018-02-08 21:45:20,127Z   main - DEBUG Getting initial state
2018-02-08 21:45:20,133Z   main - INFO Starting tap: tap-env/bin/tap-zendesk-chat --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
2018-02-08 21:45:20,135Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2018-02-08 21:45:20,667Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
2018-02-08 21:45:21,096Z    tap - INFO HTTP request to "chats" endpoint took 0.497s, returned status code 400
2018-02-08 21:45:21,096Z    tap - CRITICAL 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251
2018-02-08 21:45:21,097Z    tap - Traceback (most recent call last):
2018-02-08 21:45:21,097Z    tap -   File "tap-env/bin/tap-zendesk-chat", line 11, in <module>
2018-02-08 21:45:21,097Z    tap -     sys.exit(main())
2018-02-08 21:45:21,097Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 112, in main
2018-02-08 21:45:21,097Z    tap -     raise exc
2018-02-08 21:45:21,097Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 109, in main
2018-02-08 21:45:21,097Z    tap -     main_impl()
2018-02-08 21:45:21,097Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 105, in main_impl
2018-02-08 21:45:21,097Z    tap -     sync(ctx)
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 91, in sync
2018-02-08 21:45:21,098Z    tap -     stream.sync(ctx)
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/streams.py", line 130, in sync
2018-02-08 21:45:21,098Z    tap -     self._pull(ctx, "chat", "end_timestamp", full_sync=full_sync),
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/streams.py", line 97, in _pull
2018-02-08 21:45:21,098Z    tap -     search = ctx.client.request(self.tap_stream_id, url=next_url)
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
2018-02-08 21:45:21,098Z    tap -     ret = target(*args, **kwargs)
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/http.py", line 34, in request
2018-02-08 21:45:21,098Z    tap -     response.raise_for_status()
2018-02-08 21:45:21,098Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
2018-02-08 21:45:21,098Z    tap -     raise HTTPError(http_error_msg, response=self)
2018-02-08 21:45:21,098Z    tap - requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251
2018-02-08 21:45:21,122Z   main - INFO State update: adding bookmarks.agents.offset.id = null
2018-02-08 21:45:21,122Z   main - INFO State update: adding bookmarks.chats.chat.end_timestamp = "2016-01-01T00:00:00Z"
2018-02-08 21:45:21,122Z   main - INFO State update: adding bookmarks.chats.offset.chat.next_url = "https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251"
2018-02-08 21:45:21,122Z   main - INFO State update: adding currently_syncing = "chats"
2018-02-08 21:45:21,122Z   main - DEBUG Saving state: {'currently_syncing': 'chats', 'bookmarks': {'agents': {'offset': {'id': None}}, 'chats': {'chat.end_timestamp': '2016-01-01T00:00:00Z', 'offset': {'chat.next_url': 'https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251'}}}}
2018-02-08 21:45:21,125Z target - INFO Exiting normally
2018-02-08 21:45:21,158Z   main - INFO Target exited normally with status 0
2018-02-08 21:45:21,160Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2016-01-01T00%3A00%3A00Z+TO+%2A%5D&page=251". Target succeeded.

**Comment by nick-mccoy** [comment]
Hi @TomaszE, sorry to hear you're having issues tap-zendesk.  It's not immediately clear to me what's causing the error, but I will add this issue to our queue and we will try to resolve it as quickly as possible.  In the meantime, I see you posted in the Singer slack, so maybe someone from the community will be able to help.

**Comment by TomaszE** [comment]
Hi @nick-mccoy ,

Thanks for that. We have done some investigation - and we are fairly confident that there is a row limit on table chat. The error above says it can't load page 251 - with 40 items per page integration is able to load first 250 pages - and stops when it reaches 10000 rows and can't load 10001 row which is placed on a 251st page.

I had a quick catch up with our Zendesk Chat account manager - and as per and Zendesk - the only limitation from Zendesk side is 700 rpm and they do not limit anything else.

Hope that helps?

**Comment by b-ryan** [comment]
Hey there,

I was just testing this out and can confirm the behavior for the test account I am using. This URL works just fine, even though there is no data:

https://www.zopim.com/api/v2/chats/search?q=type:chat&page=250

it returns 

```
{
    "results": [],
    "count": 2,
    "prev_url": "https://www.zopim.com/api/v2/chats/search?q=type%3Achat&page=249",
    "next_url": null
}
```

But once you ask for page 251 (or any page after) it returns a 400 with this error:

```
{
    "description": "An error occurred trying to search",
    "error": "SearchError"
}
```

I think Zendesk just has a bug in their API. This needs to be taken up with them.

**Comment by TomaszE** [comment]
Hi @b-ryan 

Thanks, I have escalated it to Zendesk Chat.

Quick question - correct me if I'm wrong, please - if that would be a bug in their API - other services would have the same issue? We have moved from Fivetran where integration was working fine, to Stitch where we do have this problem - I'm not an expert at all - just using my own logic.

Thanks

**Comment by b-ryan** [comment]
Hey @TomaszE  - that's a good point. Yes other services would have this issue, but reasons I can think of why Fivetran are not affected might be

- It's a new bug (but maybe this is unlikely considering it would have had to be introduced between the time you switched)
- More likely, Fivetran may not use the same endpoint we are using. There are other ways to extract chats from the API.

**Comment by TomaszE** [comment]
HI @b-ryan Thank you, I will speak with Zendesk then and keep you guys updated. :)

**Comment by TomaszE** [comment]
so here is my reply from Zendesk:

> With regards to your issue, our Dev team are already looking into this as we speak.
> 
> Our current workaround for this is to use the Search Chat endpoint:
> https://developer.zendesk.com/rest_api/docs/chat/chats#search-chats and simply use a smaller datetime range for your search.

Not sure are they will even try to fix it - as on their website, there is a limit. Are we able to chunk that in more searches? In my case, 10k rows are going back to November, which means I don't have even 6month of data.

**Comment by b-ryan** [comment]
Hey @TomaszE thanks for checking into that.

I am implementing he change to chunk into more searches. The way I am implementing it, the tap needs to be configured with some number of days to break up the date range. So if that were 30 days, the search would be broken up into one search per month roughly.

I would like to set up a sensible default number of days so that you don't experience issues. Basically, we need for there to never be more than 10k chats over that number of days. You said you have 10k rows going back to November, so that's roughly 3 months. I am thinking the default can be 60 so that your sync completes without needing to make too many additional requests.

**Comment by TomaszE** [comment]
Hi @b-ryan ,

Great, that sounds great - 60days would be def enough for us!

Thank you !

**Comment by TomaszE** [comment]
Hi, :)

Me again, we are still experiencing the same issue - with the same error.

Zendesk was investigating the case and here is their reply:

> > 
> I have got this update -
> 
> "It seems that the search chat endpoint is limited to 10k records as per our engineers:
> Yeah search api gives limited results, but you can narrow down the search.
> 
> The other api, which lists all chats, will give all results and will go beyond 10,000 records.
> 
> So in their situation, they are filtering chats by date:
> We have set up the integration to get data since 01/01/2016 but in table chats I have exactly 10k rows going back to 25th Nov 2017, and no new data are being replicated ( for example for yesterday I have only 10% data up to 9AM GMT - where we started the sync.)
> 
> it is expected that using the Search chat endpoint to only get 10k results
> 
> Another one they can try is to use the all chats endpoint. This will return all chats but with no filter. They can then do the filtering on their end outside of Chat."



So it does look like if we will be using Search as an endpoint - it will always be limited to 10k results.

Only way to avoid it is to use different ( all chats ) endpoint.

**Comment by b-ryan** [comment]
@TomaszE can you provide logs from the most recent sync where this error occurred?

**Comment by TomaszE** [comment]
@b-ryan 
Sure, run yesterday - checking hoping that Zendesk have fixed it from their side, 

Error : 
`400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251`


Logs


> 2018-02-22 08:32:10,943Z   main - INFO Running tap-zendesk-chat version 0.1.10 and target-stitch version 1.7.0
> 2018-02-22 08:32:11,049Z   main - INFO Starting tap to discover schemas: tap-env/bin/tap-zendesk-chat --config /tmp/tap_discover_config.json --discover
> 2018-02-22 08:32:11,786Z    tap - INFO HTTP request to "departments" endpoint took 0.558s, returned status code 200
> 2018-02-22 08:32:11,904Z    tap - INFO HTTP request to "account" endpoint took 0.117s, returned status code 403
> 2018-02-22 08:32:11,905Z    tap - INFO Ignoring 403 from account endpoint - this must be an integrated Zendesk account. This endpoint will be excluded from discovery.
> 2018-02-22 08:32:11,943Z   main - INFO Tap exited normally.
> 2018-02-22 08:32:11,944Z   main - INFO Saving list of discovered streams
> 2018-02-22 08:32:11,997Z   main - INFO Saving structure of stream agents
> 2018-02-22 08:32:12,031Z   main - INFO Saving structure of stream chats
> 2018-02-22 08:32:12,044Z   main - INFO Saving structure of stream shortcuts
> 2018-02-22 08:32:12,054Z   main - INFO Saving structure of stream triggers
> 2018-02-22 08:32:12,067Z   main - INFO Saving structure of stream bans
> 2018-02-22 08:32:12,081Z   main - INFO Saving structure of stream departments
> 2018-02-22 08:32:12,093Z   main - INFO Saving structure of stream goals
> 2018-02-22 08:32:12,112Z   main - INFO Getting list of selected properties
> 2018-02-22 08:32:12,171Z   main - DEBUG Getting initial state
> 2018-02-22 08:32:12,175Z   main - INFO Starting tap: tap-env/bin/tap-zendesk-chat --config /tmp/tap_config.json --properties /tmp/properties.json --catalog /tmp/catalog.json --state /tmp/tap_state.json
> 2018-02-22 08:32:12,184Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
> 2018-02-22 08:32:12,645Z target - INFO Using Stitch import URL https://api.stitchdata.com/v2/import/batch
> 2018-02-22 08:32:12,992Z    tap - INFO HTTP request to "chats" endpoint took 0.466s, returned status code 400
> 2018-02-22 08:32:12,993Z    tap - CRITICAL 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251
> 2018-02-22 08:32:12,994Z    tap - Traceback (most recent call last):
> 2018-02-22 08:32:12,994Z    tap -   File "tap-env/bin/tap-zendesk-chat", line 11, in <module>
> 2018-02-22 08:32:12,995Z    tap -     sys.exit(main())
> 2018-02-22 08:32:12,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 112, in main
> 2018-02-22 08:32:12,995Z    tap -     raise exc
> 2018-02-22 08:32:12,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 109, in main
> 2018-02-22 08:32:12,995Z    tap -     main_impl()
> 2018-02-22 08:32:12,995Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 105, in main_impl
> 2018-02-22 08:32:12,996Z    tap -     sync(ctx)
> 2018-02-22 08:32:12,996Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/__init__.py", line 91, in sync
> 2018-02-22 08:32:12,996Z    tap -     stream.sync(ctx)
> 2018-02-22 08:32:12,996Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/streams.py", line 144, in sync
> 2018-02-22 08:32:12,996Z    tap -     self._pull(ctx, "chat", "end_timestamp", full_sync=full_sync),
> 2018-02-22 08:32:12,997Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/streams.py", line 111, in _pull
> 2018-02-22 08:32:12,998Z    tap -     search_resp = ctx.client.request(self.tap_stream_id, url=next_url)
> 2018-02-22 08:32:13,003Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff.py", line 286, in retry
> 2018-02-22 08:32:13,003Z    tap -     ret = target(*args, **kwargs)
> 2018-02-22 08:32:13,003Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zendesk_chat/http.py", line 34, in request
> 2018-02-22 08:32:13,003Z    tap -     response.raise_for_status()
> 2018-02-22 08:32:13,003Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
> 2018-02-22 08:32:13,003Z    tap -     raise HTTPError(http_error_msg, response=self)
> 2018-02-22 08:32:13,003Z    tap - requests.exceptions.HTTPError: 400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251
> 2018-02-22 08:32:13,027Z   main - INFO State update: adding bookmarks.agents.offset.id = null
> 2018-02-22 08:32:13,027Z target - INFO Exiting normally
> 2018-02-22 08:32:13,027Z   main - INFO State update: adding bookmarks.chats.chat.end_timestamp = "2017-01-01T00:00:00Z"
> 2018-02-22 08:32:13,027Z   main - INFO State update: adding bookmarks.chats.offset.chat.next_url = "https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251"
> 2018-02-22 08:32:13,027Z   main - INFO State update: adding currently_syncing = "chats"
> 2018-02-22 08:32:13,027Z   main - DEBUG Saving state: {'bookmarks': {'chats': {'offset': {'chat.next_url': 'https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251'}, 'chat.end_timestamp': '2017-01-01T00:00:00Z'}, 'agents': {'offset': {'id': None}}}, 'currently_syncing': 'chats'}
> 2018-02-22 08:32:13,071Z   main - INFO Target exited normally with status 0
> 2018-02-22 08:32:13,072Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "400 Client Error: BAD REQUEST for url: https://www.zopim.com/api/v2/chats/search?q=type%3Achat+AND+end_timestamp%3A%5B2017-01-01T00%3A00%3A00%2B00%3A00+TO+2017-03-02T00%3A00%3A00%2B00%3A00%5D&page=251". Target succeeded.

**Comment by b-ryan** [comment]
Great thanks.

The URL that is failing is 

https://www.zopim.com/api/v2/chats/search?q=type:chat+AND+end_timestamp:[2017-01-01T00:00:00+00:00+TO+2017-03-02T00:00:00+00:00]&page=251


Which essentially means it is asking for the 251st page of chats between January 1 and March 2 of 2017. I believe that what is happening is there are more than 10k in this time range. This was the sort of thing I was worried about in my comment here: https://github.com/singer-io/tap-zendesk-chat/issues/6#issuecomment-365978038 

Are you able to confirm if I am correct about this (that there are more than 10k chats in that time)?

The easiest option at this point is to lower the default number of days searched from 60 down to something that will work for you. Perhaps 14 or 30?

If that is not going to work, I don't think we can resort to using the endpoint to get all chats very reliably. Using it every time would just be too much data to pass through the tap every time - it would result in very slow syncs for everyone. Even if we used that endpoint for just the first sync, that first sync could fail, at which point the tap would begin using the search endpoint and we are back to square one.

If lowering the interval is not going to work, I think it would require changing the tap to be more intelligent about this situation - it would have to try to dynamically lower the interval. That could be tricky to do properly though, so I would like to try to avoid it.

**Comment by TomaszE** [comment]
Hey @b-ryan ,

Just checked again - on old fivetran zopim tables - between 2017-01-01 and 2017-03-03 i had 16k rows.  which is less then 60 days. 

I've checked it within : 
40 days - 11k
30 days - 8.8k

I do not think we have biggest customer base or number of contacts - if it won't slow down to  much - you are right, it may be worth to break it to 14 days - for people who have bigger chat demand than us. for us 30 days will work.

**Comment by b-ryan** [comment]
Ok let's try out 14 and hope this fixes the issue.
